title: Elton Teaching Resources
description: Test
theme: just-the-docs

url: https://tjelton.github.io/Elton-Teaching

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
